### ISSUE TITLE
Cursor disappears after closing a n-list

### ISSUE THREAD

**Issue by hcgraf** [psprint/zsh-navigation-tools#11]
Hi,

I just realized that my cursor disappears after any n-list is closed. It re-appears after closing some other programs, e.g. vim.

This problem is fixed by replacing "cvvis" by "cnorm" in the file n-list.
"cvvis" doesn't seem to have any effect in my terminals (konsole/yakuake with tmux).

Any idea what could be the reason for this?

Regards
Hagen

**Comment by hcgraf** [comment]
Further evaluation shows that this seems to be a problem with tmux, or my configuration of it…
Anybody using this inside tmux?

**Comment by psprint** [comment]
I confirm that. System is OS X, iTerm2 and Terminal – when on tmux, cursor is left invisible after exiting any tool. Fixed by also echoing cnorm.

**Comment by hcgraf** [comment]
Wow, very fast reaction, thank you!
