### ISSUE TITLE
"Fuzzy search" without delimiting continuous strings?

### ISSUE THREAD

**Issue by stevenharman** [psprint/zsh-navigation-tools#12]
Currently, you can search for multiple substrings by delimiting each substring with a space character. e.g., If I were searching history (via `n-history`) for a command to purge a Git remote:

```shell
git+purge
#=> git remote purge origin
```

I was wondering if there were a way to enable a "fuzzy search" such that you need not delimit the two substrings, `git` and `purge`, via a space character. e.g.,

```shell
gitpurge
#=> git remote purge origin
```

I realize it's trivial to type the space character, and I can train myself to do it. But if there's a simple way to enable such an option, it might be nice as many other navigation tools allow for this kind of "fuzzy" searching, and my muscle memory uses it instinctively.

Thank you!

**Comment by psprint** [comment]
The best that I can do is in following patch. It allows single error to occur. Typing "gitremote" will match "git remote". I will rather not commit this patch, as it makes e.g. "a" match every entry in history. ZNT is implemented in pure ZSH, it's hard to do that advanced functionality while not loosing high speed of operation. On the other hand it allows very sophisticated things to be implemented, like the multi-word matching, in just few lines of code. Also, installation is trivial, no C-implemented binary is required.

PS. Maybe I could use the "accept one error" for longer query strings, keeping things like "a" normal, strict. Will think about that.

diff --git a/n-list b/n-list
index 55c0851..eb56581 100644
--- a/n-list
+++ b/n-list
@@ -266,7 +266,7 @@ while (( 1 )); do
                 search_pattern="${search_buffer// ##/*~^*}"
                 colsearch_pattern="${search_buffer// ##/|}"

-                list=( "${(@M)list:#(#i)*$~search_pattern*}" )
+                list=( "${(@M)list:#(#ia1)*$~search_pattern*}" )
                 last_element="$#list"
             fi

@@ -285,7 +285,7 @@ while (( 1 )); do

             if [ -n "$colsearch_pattern" ]; then
                 local red=$'\x1b[00;31m' reset=$'\x1b[00;00m'
-                disp_list=( "${(@)disp_list//(#mi)($~colsearch_pattern)/$red${MATCH}$reset}" )
+                disp_list=( "${(@)disp_list//(#mia1)($~colsearch_pattern)/$red${MATCH}$reset}" )
             fi

             # We have display list, lets replace newlines with "\n" when needed (1/2)

**Comment by psprint** [comment]
The best that I can do is in following patch. It allows single error to occur. Typing "gitremote" will match "git remote". I will rather not commit this patch, as it makes e.g. "a" match every entry in history. ZNT is implemented in pure ZSH, it's hard to do that advanced functionality while not loosing high speed of operation. On the other hand it allows very sophisticated things to be implemented, like the multi-word matching, in just few lines of code. Also, installation is trivial, no C-implemented binary is required.

PS. Maybe I could use the "accept one error" for longer query strings, keeping things like "a" normal, strict. Will think about that.

<pre>
diff --git a/n-list b/n-list
index 55c0851..eb56581 100644
--- a/n-list
+++ b/n-list
@@ -266,7 +266,7 @@ while (( 1 )); do
                 search_pattern="${search_buffer// ##/*~^*}"
                 colsearch_pattern="${search_buffer// ##/|}"

-                list=( "${(@M)list:#(#i)*$~search_pattern*}" )
+                list=( "${(@M)list:#(#ia1)*$~search_pattern*}" )
                 last_element="$#list"
             fi

@@ -285,7 +285,7 @@ while (( 1 )); do

             if [ -n "$colsearch_pattern" ]; then
                 local red=$'\x1b[00;31m' reset=$'\x1b[00;00m'
-                disp_list=( "${(@)disp_list//(#mi)($~colsearch_pattern)/$red${MATCH}$reset}" )
+                disp_list=( "${(@)disp_list//(#mia1)($~colsearch_pattern)/$red${MATCH}$reset}" )
             fi

             # We have display list, lets replace newlines with "\n" when needed (1/2)
</pre>

**Comment by stevenharman** [comment]
If it makes the code messy, or execution slow, I think it's smart to _not_ do it. Like I said, it's easy enough to just hit the `Spacebar`. :smile:

**Comment by psprint** [comment]
I forwarded this to zsh-users. I think there is a big chance of "gitpush" => "git push", as it should be trivial to implement. Not sure about your "gitpurge" case:

http://www.zsh.org/mla/users/2015/msg01377.html
