### ISSUE TITLE
Color style for current in n-history?

### ISSUE THREAD

**Issue by neagle** [psprint/zsh-navigation-tools#13]
I saw this come down in my most recent update from `oh-my-zsh` and it's great. My only question is about `n-history`: I don't see any visual indicator of where my cursor is. I see the "Current #N" change at the bottom as I go up and down, but it's hard to use without that.

Is that something I can easily fix somehow, or possibly a setting that could be fixed on the repo level?

![2016-02-02 at 1 38 pm](https://cloud.githubusercontent.com/assets/176993/12760032/5400115a-c9b2-11e5-8d9b-8dc084cfe60b.png)

Thanks for any help you're able to provide!

**Comment by psprint** [comment]
The current-line mark can be changed. Open ~/.config/znt/n-history.conf and change:

local active_text=underline

to:

local active_text=reverse

What terminal do you use with tmux?

Best regards,
Sebastian Gniazdowski

**Comment by neagle** [comment]
Ah ha! I didn't realize it had generated config for me. That's perfect. Thanks a bunch of answering my question.

I use iTerm2 (I'm on a Mac) for my tmuxing. :)

Cheers!

**Comment by psprint** [comment]
Have Mac/iTerm2 here, have to admit it does reproduce under tmux, thanks
for information!
​

**Comment by psprint** [comment]
PS. Found this:

http://hoppsjots.org/?p=177

Best regards,
Sebastian Gniazdowski

**Comment by neagle** [comment]
Nice! Thanks for that investigation: I hadn't really realized I had a problem with underlines that I wasn't even aware of. Cheers!
