### ISSUE TITLE
Controlling colors and bolding

### ISSUE THREAD

**Issue by jasontibbitts** [psprint/zsh-navigation-tools#15]
I find it very jarring to hit ^R and be presented with a page of loud white bold text when my regular shells are rather sedate.  I use solarized-dark and the text is mostly a medium grey.  Pressing ^R gives me a page that's entirely bold with the text in the brightest color solarized offers.

I set local bold=0 in n-list.conf, and this makes the list come up unbolded (but still with white text).  However, if I press any key, the history entries (but not the border, title, or "Filtering with" line at the bottom) immediately become bold.

I guess white/black is hardcoded in several places i the code, which would explain the bright color.  I'm not sure why the bolding happens.  I guess it wouldn't be too hard to make the color combination configurable.

**Comment by psprint** [comment]
I've added two commits (the extra one here in Github was amended), one for the bold setting, one for configuring default color pair. New configuration block (n-list.conf):

```zsh
# Main color pair (foreground/background)
local colorpair="white/black"
```

**Comment by jasontibbitts** [comment]
Thanks!
