### ISSUE TITLE
oh-my-zsh integration: configuration in zshrc

### ISSUE THREAD

**Issue by doubleloop** [psprint/zsh-navigation-tools#16]
zsh-navigation-tools is using internal config files copied to ~/.config/znt/, and I do not see the way to propagate configuration from zshrc.. It would be awesome if such flags like NLIST_INSTANT_SELECT (psprint/zsh-navigation-tools#14 (comment)) could be set in zshrc (so all custom configuration is in one place and easy to deploy/share).

**Comment by psprint** [comment]
Implemented in `v2.1.12`: https://github.com/psprint/zsh-navigation-tools#configuration

**Comment by psprint** [comment]
I see there are no issues about the change. Thanks for the nice idea! Quite better to have all the variables in zshrc.
