### ISSUE TITLE
[zsh-navigation-tools] n-kill freezes whole shell on second page

### ISSUE THREAD

**Issue by kapsh** [psprint/zsh-navigation-tools#18]
I've just enabled zsh-navigation-tools plugin in OMZ and soon I figured out that `n-kill` command can cause 100% CPU and up to 14 GB RAM usage of currently running zsh process.
To reproduce it, one can launch `n-kill` and try to scroll down to second page with arrow key or page down.

**Comment by psprint** [comment]
What is the system and Zsh version? I'll install the system on virtualBox and try to reproduce (it doesn't reproduce on OS X).

**Comment by kapsh** [comment]
zsh 5.2 on Gentoo Linux _// yeah, I know what you can say about it_
Resource leak appears on zsh 5.0.5 too but I didn't reproduce it on 5.0.7 on Debian host. Maybe problem is really in my environment, but if you still want to explore this — I prepared for you minimal image of my system with zsh settings for root. Download link was sent to gmail address which I found in git log of this repo.

**Comment by psprint** [comment]
Thanks I'm downloading the link (5 hours more, hope for no interrupts).

**Comment by psprint** [comment]
I was chrooting into the system from NixOS and Arch Linux and illegal instruction in /bin/zsh was reported. LiveCD for newest Gentoo doesn't load into VMBox and for previous version it crashes when booting :) Will try some other OS in spare time, maybe you have an idea from which chrooting would work?

**Comment by kapsh** [comment]
Sorry, this looks like my fault. 
I can't say why you can't boot with Gentoo LiveCD, but I forgot that my system was built with "march=native" on Intel Skylake. Maybe you have some older CPU which doesn't suport some instructions used in compiled binaries. 
I can rebuild that image for generic x86-64 if you can redownload it later.

**Comment by psprint** [comment]
Yeah that would be great, I will gladly re-download, I wonder why such a simple program can hog shell. Thought too later about different CPU, my is 2,3 GHz Intel Core i5.

**Comment by kapsh** [comment]
mkay, I will send you link to image later. 
I found on everymac.com that your model has Sandy Bridge (2nd gen).

**Comment by psprint** [comment]
I will be chrooting on VirtualBox, so probably best to use i686 for the compilation

**Comment by kapsh** [comment]
IIRC changing architecture of installed system is unsuported in Gentoo, but maybe I can perform some weird hack to do this. Are you sure you can not use x86-64 on VM?

PS I figured out that n-kill dies with message `_nlist_colorify_disp_list:6: fatal error: out of heap memory`. I think some race condition or endless loop happens there.

**Comment by psprint** [comment]
You're right, it supports x86-64, I just wanted to provide some most general architecture, but 64 bit is better.

Can you run some stuff to debug the issue? Here is small script-program, extracted code from n-list, that contains the line of code `_nlist_colorify_disp_list:6` you gave:

http://sprunge.us/NHgf

This script will generate /tmp/reply2.txt, could you sent it to me? If the program hangs then it will be success. Next, if it doesn't hang, then here is patch on n-list:

http://sprunge.us/OhdL

If patching is a problem here is complete n-list file:

http://sprunge.us/dIBh

The file "n-list" should be compied to ~/.config/znt/zsh-navigation-tools if you used installer, or to directory where your plugin manager keeps plugins. The same with the patch, it should be applied to n-list file via `patch -p1 < n-list.diff`. New n-list will generate /tmp/reply.txt, could you send it to me? 

I think you've found bug in upstream Zsh. I guess you have a process in your process list with a name that disturbs Zshell's patterns code. That's why it reproduces only on one machine. The files reply*.txt will contain the process list and I will be able to examine which string disturbs Zshell's pattern code.

**Comment by kapsh** [comment]
First script hangs with "out of heap memory" error. Here is result: [reply2.txt](https://github.com/psprint/zsh-navigation-tools/files/299341/reply2.txt)

After patching n-list: [reply.txt](https://github.com/psprint/zsh-navigation-tools/files/299344/reply.txt)

**Comment by psprint** [comment]
OK, it's a bug in Zsh, I have bug report ready. Do you maybe want me to mention you as the finder of the bug? By name or by Github nick?

Test program revealing the issue, with a long line from your submitted files. Let's hope this is fixable and not "Zsh is slow for long lines".

```zsh
#!/usr/bin/env zsh-5.0.2

emulate -LR zsh
setopt extendedglob

typeset -a list disp_list
list=( "3226  1802 /opt/google/chrome/chrome --type=renderer --enable-lcd-text --enable-features=DownloadResumption,IncidentReportingModuleLoadAnalysis<SafeBrowsingIncidentReportingServiceFeatures,IncidentReportingSuspiciousModuleReporting<SafeBrowsingIncidentReportingServiceFeatures,LinuxObsoleteSystemIsEndOfTheLine<LinuxObsoleteSystemIsEndOfTheLine,PrintPreviewDistiller,*UsePasswordSeparatedSigninFlow<PasswordSeparatedSigninFlow,WebFontsIntervention<WebFontsIntervention,*WebRTC-EnableWebRtcEcdsa<WebRTC-EnableWebRtcEcdsa,brotli-encoding<BrotliEncoding,enable-automatic-password-saving --disable-features=RenderingPipelineThrottling<RenderingPipelineThrottling --force-fieldtrials=AppBannerTriggering/Aggressive/*AutoReloadExperiment/FlagEnabled/*AutoReloadVisibleOnlyExperiment/FlagEnabled/AutofillProfileOrderByFrecency/Enabled/*BrotliEncoding/Enabled/CaptivePortalInterstitial/Enabled/*ChildAccountDetection/Disabled/*ClientSideDetectionModel/Model0/*CrossDevicePromo/28DaySingleProfile/EnableSessionCrashedBubbleUI/EnabledByFlag/*ExtensionActionRedesign/Enabled/*ExtensionDeveloperModeWarning/Default/*GFE/Default/InstanceID/Enabled/LinuxObsoleteSystemIsEndOfTheLine/EndOfLine/MaterialDesignDownloads/Enabled/*NewProfileManagement/Command-Line-Disabled/*OmniboxBundledExperimentV1/Unused_2/*OutOfProcessPac/Default/*PageRevisitInstrumentation/Default/PasswordBranding/Disabled/*PasswordGeneration/Disabled/*PasswordManagerSettingsMigration/Disable/PasswordSeparatedSigninFlow/Default/*QUIC/FlagEnabled/*RenderingPipelineThrottling/Disabled/ReportCertificateErrors/ShowAndPossiblySend/*ResourcePriorities/Launch50pct_11011_1_1_10/SHA1IdentityUIWarning/Enabled/SHA1ToolbarUIJanuary2016/Warning/SHA1ToolbarUIJanuary2017/Error/SSLCommonNameMismatchHandling/Enabled/*SafeBrowsingIncidentReportingService/Default/SafeBrowsingIncidentReportingServiceFeatures/WithSuspiciousModuleReporting/SafeBrowsingUnverifiedDownloads/DisableByParameterMostSbTypes2/SafeBrowsingUpdateFrequency/Default/*SimpleCacheTrial/ExperimentYes2/SyncHttpContentCompression/Disabled/*UMA-Population-Restrict/normal/*UMA-Uniformity-Trial-1-Percent/group_61/*UMA-Uniformity-Trial-10-Percent/default/*UMA-Uniformity-Trial-100-Percent/group_01/*UMA-Uniformity-Trial-20-Percent/group_03/*UMA-Uniformity-Trial-5-Percent/group_04/*UMA-Uniformity-Trial-50-Percent/group_01/*UseDelayAgnosticAEC/DefaultEnabled/*WebFontsIntervention/Enabled/WebRTC-EnableWebRtcEcdsa/Default/ --primordial-pipe-token=F02F1A91C1338A95D3C111314BA6B87A --lang=en-US --enable-crash-reporter=831AB4A2-FDF7-4D2B-9BE0-F22377348434, --extension-process --enable-webrtc-hw-h264-encoding --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --show-saved-copy=secondary --blink-settings=fetchDeferLateScripts=true,fetchIncreaseFontPriority=true,fetchIncreasePriorities=true --enable-suggestions-with-substring-match -" )

_nlist_colorify_disp_list() {
    local col=$'\x1b[00;34m' reset=$'\x1b[0m'
    NLIST_COLORING_PATTERN="([^ /\\\\]##[^0-9/\\\\ ]##[^/\\\\]#(#e))"
    disp_list=( "${(@)disp_list//(#mi)$~NLIST_COLORING_PATTERN/$col${MATCH}$reset}" )
}

disp_list=( "${(@)list[1, 50]}" )
echo "Starting"
_nlist_colorify_disp_list
echo "Done"
```

**Comment by kapsh** [comment]
Yeah, this test dies with OOM too. 

Sure you can mention my nickname. And leave a link to your report here please. 
Thanks for help!

**Comment by sgniazdowski** [comment]
I have sent the report, but MLA archive is currently down: http://www.zsh.org/cgi-bin/mla/wilma/workers
My message will be there when it's up. Title will be "[BUG] Long line makes pattern matching (by //) hog Zsh"

Thanks for your effort!

**Comment by psprint** [comment]
I have sent the report, but MLA archive is currently down: http://www.zsh.org/cgi-bin/mla/wilma/workers My message will be there when it's up. Title will be "[BUG] Long line makes pattern matching (by //) hog Zsh"

Thanks for your effort!

**Comment by psprint** [comment]
I've provided a quick workaround for the problem (v2.2), could you try? It will colorify less strictly (like on the image – zeroes shouldn't be highlighted), but without any CPU hog (hopefully).

![znt1](https://cloud.githubusercontent.com/assets/6049288/15807842/c4c9400c-2b67-11e6-9c2c-812b91784924.png)

**Comment by kapsh** [comment]
No, version at 063df2cda1d24b18c6a7387a782cfa2288c97d34 eat all memory too.

**Comment by psprint** [comment]
Sorry I forgot to mention that removal of configuration files is needed, i.e.

```zsh
rm -f ~/.config/znt/*.conf
```

You can remove only `~/.config/znt/n-kill.conf` but then it will be copied after ~7 restarts of Zsh (there's a random check to optimize plugin's startup :d https://github.com/psprint/zsh-navigation-tools/blob/f49f910d239ae5bc6e1a5bb34930307b4f4e3ffe/zsh-navigation-tools.plugin.zsh#L35-L49)

**Comment by kapsh** [comment]
Config's removal didn't change anything.

**Comment by psprint** [comment]
That's really weird, I run n-kill on the input that I've received and it runs enough fast. Have some other optimization on mind, maybe tomorrow things get better..

**Comment by psprint** [comment]
I've added one more modification to the configuration file, maybe now? Turns out the errors can be suppressed, I see good coloring. Commit d63ee84.

**Comment by kapsh** [comment]
Sorry, my bad. 063df2cda1d24b18c6a7387a782cfa2288c97d34 is good. Maybe I've deleted configs in the wrong place at first time. 
There is no need in d63ee8451afb5bff2cc53d9ff20ed73accb73434 I think.

**Comment by psprint** [comment]
Great! d63ee84 highlights better, no errors at all, I think only Cygwin will be problematic (installing Windows on VBox to check), I apparently removed part of pattern dedicated to Cygwin, it was the cause of Zsh hog

**Comment by psprint** [comment]
I've just submitted the update to OMZ where you first created issue. Thanks for staying on it for that long that we could track such an obscure bug! I think we did a great job

**Comment by kapsh** [comment]
Thank you.
