### ISSUE TITLE
Selection at the bottom

### ISSUE THREAD

**Issue by cgcgcg** [psprint/zsh-navigation-tools#19]
Hi!

I really like `n-history`. It's a great tool! Would it be possible to implement and option so that selection happens at the bottom of the screen instead of the top? I'm using a fairly large terminal window, and it would be nice if the best candidate were just above the search string..

Thanks!

**Comment by psprint** [comment]
Hello!
There is other plugin written for this purpose:

https://github.com/psprint/history-search-multi-word

ZNT' advantage is private history and themes. When Zsh 5.3 will be released, one will be able to use 256 colors with ZNT, which will allow to have the full-screen an additional pleasant effect, when selected with sedative or other colors of choice. That's the situation it's your choice :) Thanks!

**Comment by cgcgcg** [comment]
Thanks, history-search-multi-word works!
