### ISSUE TITLE
When znt is installed, some env vars are acting weird

### ISSUE THREAD

**Issue by vadali** [psprint/zsh-navigation-tools#21]
Hey,
I tried using znt, which is pretty nice. When I activate the plugin, I get the weirdest thing, and was hoping you could explain it. 

When the plugin is activated, the shell variables $1 $2 etc are bound to some znt file names, e.g:
```
> echo $1
n-aliases.conf
> echo $2
n-env.conf
> echo $3
n-history.conf
> echo $4
n-list.conf
> echo $5
n-panelize.conf
> echo $6
n-cd.conf
> echo $7
n-functions.conf
> echo $8
n-kill.conf
> echo $9
n-options.conf
```
I discovered it because my emacs is aliased to "Emacs $@" so I was getting all these files opened up every time I opened emacs..

Why is this happening?

Thanks!

**Comment by psprint** [comment]
To explain: when the plugin loads, at startup, it uses $1, $2, $3, ... positional parameters. It can do that – once, at Zsh startup. Then your shell assigns them again to other values.

That said, there's code in ZNT that clears positional parameters, just for cleanliness:

https://github.com/psprint/zsh-navigation-tools/blob/master/zsh-navigation-tools.plugin.zsh#L52-L53

It was added on April 20, 2016:

https://github.com/psprint/zsh-navigation-tools/commit/1da2d330ad84835b3bc7687b7036812f74b88c3d

Maybe your ZNT is older? Do the two lines exist in your zsh-navigation-tools.plugin.zsh file?

That said, when you alias emacs to "Emacs $@", you cause your shell to paste $1, $2, $3, ... to Emacs command line. This is how aliasing works. It's sufficient to do alias emacs="Emacs". If you would want to use $@, then create a function:

```zsh
function emacs() {
    Emacs "$@"
}
```

**Comment by vadali** [comment]
Hey, thanks for pointing this out! Yes, I indeed did not pull for a long time, and the new version fixes it. 

Regarding aliases, yes, $@ pastes the vars into the alias, that is how it is [recommended to set up emacs on osx](https://emacsformacosx.com/tips).. I like your idea for the function though.

Thanks for the clarification!

**Comment by psprint** [comment]
Glad to hear it's solved :)
