### ISSUE TITLE
Lists don't handle windows resizing

### ISSUE THREAD

**Issue by apjanke** [psprint/zsh-navigation-tools#9]
It would be nice if the list display were able to handle window resizing. As it is now, resizing the window causes the display to get messed up.

![list resizing](https://cloud.githubusercontent.com/assets/2618447/10184768/9786b34a-670e-11e5-8b17-ef7f5449e803.gif)

**Comment by apjanke** [comment]
I've got a PR going for this on https://github.com/apjanke/zsh-navigation-tools/tree/window-resizing. It doesn't repaint immediately upon window resize, but does on the first input after a resize.

**Comment by apjanke** [comment]
Looks like this might be pretty hard to make entirely live: there may be an issue in zsh's `zsh/curses` module with the interaction between signal handling (which happens in the case of window resizes) and read timeouts.

https://github.com/zsh-users/zsh/blob/6ff0628182ac74bbf22dc02edcc9a148f12767db/Src/Modules/curses.c#L1072-L1104

**Comment by apjanke** [comment]
Maybe not so hard after all. This works on Linux and on OS X with a Homebrew `zsh` linked against `ncurses` 6.0. Might be able to get this sorted out. I have a thread going on the zsh workers mailing list about it: http://www.zsh.org/mla/workers/2015/msg02630.html.

**Comment by psprint** [comment]
I just thought that you could unload and then load zsh/curses module

**Comment by apjanke** [comment]
I don't think that'll work. I tried it, and it had no effect. The issue might be that while `zsh/curses` gets unloaded, `ncurses` itself stays loaded, because it's unconditionally loaded for `zsh`'s own use, so whatever state is in there stays. The `zsh/curses` module is just `zsh` language bindings for `curses`, not the whole use of `curses` by the program.

```
$ otool -L /bin/zsh
/bin/zsh:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
```

**Comment by psprint** [comment]
There is a bug before 5.1.1 that can cause random behavior of colors. I was resetting zcurses state by zmodload -u. So this does serious reset of state, basically all variables that are in curses.c are reset. But if it didn't help then apparently the improper state is at lower level, as you wrote.
